name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this if your default branch is different, e.g., "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can adjust the node version as needed

      - name: Install dependencies
        run: npm install -g firebase-tools

      - name: Firebase deploy
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
